version: "3.9"

services:
  web:
    build: .
    container_name: codelms
    ports:
      - "8000:5000"
    env_file:
      - .env.production
    command: gunicorn -b 0.0.0.0:5000 "lms:create_app()"
