services:
  web:
    build: .
    container_name: codelms
    ports:
      - "8000:5000"
    env_file:
      - .env.production
    command: gunicorn -b 0.0.0.0:5000 "lms:create_app()"
    volumes:
      - .:/app       # Mount current folder to /app in container
    working_dir: /app  # Set working directory
